#!/usr/bin/python3
from datetime import datetime, date
import sys
sys.path.insert(1, '../')
from generate import generate
import gen_cfg

VERSION = sys.argv[1]
CONTRACT_ADDRESS = sys.argv[2]
CODE_ID = int(sys.argv[3])
CHAIN_ID = sys.argv[4]
LCD_URL = sys.argv[5]



PATH = './src'
FILENAME = 'constants.tsx'

HEADER = \
f'''
/******************************************************************************

BLACKJACK FRONTEND {VERSION}
AUTOGENERATED {FILENAME.upper()} FILE

CREATED:        {date.today().strftime("%d %B %Y")}
AUTHOR:         YAESHA256, Skrillah, Jensei
AFFILIATIONS:   AART, Secret
                                                                               
******************************************************************************/




'''

INJECTIONS = \
{
    "METADATA" :
    f'''BLACKJACK_VERSION : string     = "{VERSION}";              \n'''
    f'''CONTRACT_ADDRESS : string      = "{CONTRACT_ADDRESS}";     \n'''
    f'''CODE_ID : number               = {CODE_ID};                \n'''
    f'''CHAIN_ID : string               = "{CHAIN_ID}";            \n'''
    f'''LCD_URL : string               = "{LCD_URL}";            \n''',



    "CLIENT_ENDPOINTS" :
     '''this.cli = [  \n'''
     '''                                                    \n'''
     '''    [new SecretNetworkClient({                      \n'''
     '''    url: 'http://testnet.securesecrets.org:1317',   \n'''
     '''    wallet: this.wallet,                            \n'''
     '''    walletAddress: this.wallet.address,             \n'''
     f'''   chainId: '{CHAIN_ID}',                         \n'''
     '''    }),                                            \n'''
     f'''    '{CHAIN_ID}',                                   \n'''
     '''    'http://testnet.securesecrets.org:1317'],       \n'''
     '''                                                    \n'''
     '''    [new SecretNetworkClient({                      \n'''
     '''    url: 'https://lcd.testnet.secretsaturn.net',    \n'''
     '''    wallet: this.wallet,                            \n'''
     '''    walletAddress: this.wallet.address,             \n'''
     f'''    chainId: '{CHAIN_ID}',                         \n'''
     '''    }),                                             \n''' 
     f'''    '{CHAIN_ID}',                                  \n'''
     '''    'https://lcd.testnet.secretsaturn.net'],        \n'''
     '''                                                    \n'''
     '''    [new SecretNetworkClient({                      \n'''
     '''    url: 'https://api.pulsar.scrttestnet.com',      \n'''
     '''    wallet: this.wallet,                            \n'''
     '''    walletAddress: this.wallet.address,             \n'''
     f'''    chainId: '{CHAIN_ID}',                          \n'''
     '''    }),                                             \n'''
     f'''    '{CHAIN_ID}',                                   \n'''
     '''    'https://api.pulsar.scrttestnet.com'],          \n'''
     '''];                                                  \n'''
     '''                                                    \n''',
}

generate(PATH, FILENAME, HEADER, INJECTIONS, gen_cfg.OUT_DIR )



